pretrained_model_name_or_path: "stabilityai/stable-diffusion-xl-base-1.0"
pretrained_vae_model_name_or_path: "madebyollin/sdxl-vae-fp16-fix"
dataset_name: "D:/workspace/dataset/sketchall"
image_column: "image"
caption_column: "txt"
resolution: 1024
random_flip: true
train_batch_size: 1
num_train_epochs: 1
checkpointing_steps: 1000
learning_rate: 0.000005
lr_scheduler: "constant"
lr_warmup_steps: 0
mixed_precision: "fp16"
seed: 42
output_dir: "sdxl-diff"
validation_prompt: "a blouse"
report_to: "tensorboard"